= Basic tests comparisons =

== In this section we provide a comparison of the different libraries on an instance of basic tests made on a class ==

=== Presentation of the class ===
We used the `Dwarf` class to make our tests :

This class has the following fields : `String name; private double size; private double weight; private boolean hasBeard; private boolean hasHangover; SongRepository knownSongs` +
SongRepository is a helper class used to encapsulate a Collection. Its methods for modification are package protected and usable only by the dwarf whereas all methods that do not modify the collection are public.

.Show Dwarf source code
[%collapsible]
====
[source,language="java"]
----
package org.examples.Dwarf;
import java.util.Random;

public class Dwarf {
    private String name;
    private double size;
    private double weight;
    private boolean hasBeard;
    private boolean hasHangover;

    public String getName() {
        return name;
    }


    public double getSize() {
        return size;
    }

    public void setSize(double size) {
        this.size = size;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public void shave() {
        this.hasBeard = false;
    }

    public void growBeard() {
        this.hasBeard = true;
    }

    public boolean isHungover() {
        return hasHangover;
    }

    private SongRepository knownSongs = new SongRepository();

    public Dwarf(String name, double size, double weight, boolean hasBeard) {
        this.name = name;
        this.size = size;
        this.weight = weight;
        this.hasBeard = hasBeard;
        this.hasHangover = false;
    }

    public void learnSong(String newSong) {
        this.knownSongs.add(newSong);
    }

    public void sleep() {
        this.hasHangover = false;
    }

    private String drink() {
        Random rand = new Random();
        int i = rand.nextInt(this.knownSongs.size() );
        this.hasHangover = true;
        return this.knownSongs.remove(i);
    }

    private void drinkWithoutKnownSongs() {
        this.hasHangover = true;
    }

    public boolean isBearded() {
        return this.hasBeard;
    }

    private void sing(String song) {
        System.out.println(song);
    }

    public void goesToTavern() {
        if(knownSongs.isEmpty())
        {
            drinkWithoutKnownSongs();
        }else //if is not empty
        {
            sing(this.drink());
        }

    }

    public boolean isKnown(String song) {
        return this.knownSongs.contains(song);
    }

    public SongRepository getLearnedSongs() {
        return this.knownSongs;
    }
}

----
====
.Show SongRepository source code
[%collapsible]
====
[source, language="java"]
----
package org.examples.Dwarf;

import java.util.ArrayList;
public class SongRepository {

    private ArrayList<String> songs = new ArrayList<>();

    void add (String song) {
        this.songs.add(song);
    }

    public boolean contains (String song) {
        return this.songs.contains(song);
    }

    String remove (int i) {
        return songs.remove(i);
    }

    public int size () {
        return songs.size();
    }

    public boolean isEmpty(){return songs.isEmpty();}
}

----
====

=== Comparisons of the tests ===

==== testConstructor ====
This test is to ensure that the constructor properly sets the object's fields

===== Apache :


[source, language="java"]
----
Validate.isTrue(Objects.equals(dwarf.getName(), "Jeremy"));
Validate.isTrue( dwarf.getSize() == 80.4);
Validate.isTrue( dwarf.getWeight() == 90.3);
Validate.isTrue(!dwarf.isBearded());
----
===== AssertJ :
[source, language="java"]
----
assertThat(dwarf)
                .extracting(Dwarf::getName, Dwarf::getSize, Dwarf::getWeight, Dwarf::isBearded)
                .containsExactly("Jeremy", 80.4, 90.3, false);
----

===== Atlanmod :
[source, language="java"]
----
Guards.checkEqualTo(dwarf.getName(),"Jeremy");
Guards.checkEqualTo(dwarf.getSize(),80.4);
Guards.checkEqualTo(dwarf.getWeight(),90.3);
Guards.checkEqualTo(dwarf.isBearded(),false);
----
===== Guava :
[source, language="java"]
----
test = Objects.equal(dwarf.getName(), "Jeremy");
checkArgument(test, "Wrong name");

test = Objects.equal(dwarf.getSize(), 80.4);
checkArgument(test, "Wrong size");

test = Objects.equal(dwarf.getWeight(), 90.3);
checkArgument(test, "Wrong weight");

checkArgument(!dwarf.isBearded(), "We should not have beard");
fail("Expected false but is true");
----
===== Truth :
[source, language="java"]
----
assertThat(dwarf.getName()).isEqualTo("Jeremy");
assertThat(dwarf.getSize()).isEqualTo(80.4);
assertThat(dwarf.getWeight()).isEqualTo(90.3);
assertThat(dwarf.isBearded()).isFalse();
----

==== testSize ====
This test ensures that `getSize()` and `setSize()` works as intended

===== Apache :

[source, language="java"]
----

----
===== AssertJ :
[source, language="java"]
----

----

===== Atlanmod :
[source, language="java"]
----

----
===== Guava :
[source, language="java"]
----

----
===== Truth :
[source, language="java"]
----

----


==== testWeight ====
This test ensures that `getWeight()` and `setWeight()` works as intended

===== Apache :

[source, language="java"]
----

----
===== AssertJ :
[source, language="java"]
----

----

===== Atlanmod :
[source, language="java"]
----

----
===== Guava :
[source, language="java"]
----

----
===== Truth :
[source, language="java"]
----

----

==== testBeard ====
This test ensures that `shave()`,`growBeard()` and `isBearded()` works as intended

===== Apache :

[source, language="java"]
----

----
===== AssertJ :
[source, language="java"]
----

----

===== Atlanmod :
[source, language="java"]
----

----
===== Guava :
[source, language="java"]
----

----
===== Truth :
[source, language="java"]
----

----

==== testHungover ====
This test ensures that the hungover field is properly set by the dwarf going to the tavern and sleeping

===== Apache :

[source, language="java"]
----

----
===== AssertJ :
[source, language="java"]
----

----

===== Atlanmod :
[source, language="java"]
----

----
===== Guava :
[source, language="java"]
----

----
===== Truth :
[source, language="java"]
----

----

==== testSongs ====
This test ensures that the learned songs get updated when a dwarf learns a song & goes to the tavern (which causes him to forget a song and sing it).
This also ensures that the song is properly printed when sang.

===== Apache :

[source, language="java"]
----

----
===== AssertJ :
[source, language="java"]
----

----

===== Atlanmod :
[source, language="java"]
----

----
===== Guava :
[source, language="java"]
----

----
===== Truth :
[source, language="java"]
----

----

== Conclusion ==