= Examples of Preconditions from the https://github.com/google/guava[Guava] library =


[sidebar]
== Presentation of Guava
====
Guava is a set of core Java libraries from Google that includes new collection types (such as multimap and multiset), immutable collections, a graph library, and utilities for concurrency, I/O, hashing, caching, primitives, strings, and more. It is widely used on most Java projects within Google, and widely used by many other companies as well.
====

[sidebar]
== Characteristics of the library
====
Guava provides a number of *precondition checking utilities* in the https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Preconditions.java[Preconditions] class and there is 3 variants for each method.
This class contains static methods that can help to check whether it was invoked correctly (that is, whether its preconditions were met).
If the precondition is not met, the Preconditions method throws an unchecked exception to a specified type, which helps the method in which the exception was thrown communicate that its caller has made a mistake.
====

[sidebar]
== Variants

*As we said, each precondition method has 3 variants :*
[square]
* One with no extra arguments
* An extra Object argument. Any exception is thrown with the error message object.toString().
* An extra String argument, with an arbitrary number of additional Object arguments. This behaves something like printf, but for GWT compatibility and efficiency, it only allows %s indicators.

NOTE: checkNotNull, checkArgument and checkState have a large number of overloads taking combinations of primitive and Object parameters rather than a varargs array — this allows calls such as those above to avoid both primitive boxing and _varags_ array allocation in the vast majority of cases.

These test are to give practical examples of the main utilities regarding preconditions provided by this library :

[sidebar]
== Preconditions
[source,asciidoc]
|===
|Signature (not including extra args) |Description |Exception thrown on failure

|checkArgument(boolean)
|Checks that the boolean is true. Use for validating arguments to methods.
|IllegalArgumentException

|checkNotNull(T)
|Checks that the value is not null. Returns the value directly, so you can use checkNotNull(value) inline.
|NullPointerException

|checkState(boolean)
|Checks some state of the object, not dependent on the method arguments. For example, an Iterator might use this to check that next has been called before any call to remove.
|IllegalStateException

|checkElementIndex(int index, int size)
|Checks that index is a valid element index into a list, string, or array with the specified size. An element index may range from 0 inclusive to size exclusive. You don't pass the list, string, or array directly; you just pass its size. Returns index.
|IndexOutOfBoundsException

|checkPositionIndex(int index, int size)
|Checks that index is a valid position index into a list, string, or array with the specified size. A position index may range from 0 inclusive to size inclusive. You don't pass the list, string, or array directly; you just pass its size. Returns index.
|IndexOutOfBoundsException

|checkPositionIndexes(int start, int end, int size)
|Checks that start and end both are in the range [0, size] (and that end is at least as large as start). Comes with its own error message.
|IndexOutOfBoundsException
|===

For more details you can consult the extended version of the description of the methods (for each variant) on https://guava.dev/releases/snapshot/api/docs/com/google/common/base/Preconditions.html[guava preconditions]

[sidebar]
== The examples
This section shows some examples of Preconditions in guava so that we can observe the syntax

for example the checkArgument method, in its basic form with no extra arguments :

[source, Java]
Preconditions.checkArgument(boolean argument);

The test :

.Hide source code
[%collapsible%open]
====
[source, Java]
    /**
     * Testing the checkArgument Guard in Guava
     * */
    @Test
    public void testCheckArgument() {
        try {
            Preconditions.checkArgument(false, "The argument given is false");
            fail("no exception thrown, IllegalArgumentException expected");
        } catch (IllegalArgumentException expected) {
            System.out.println("correctly catched a " + expected );
        }
    }
====
The expected output :

[source, bash]
correctly catched a java.lang.IllegalArgumentException: The argument given is false