= Example assertions =

This repository holds a java projects which aims to provide examples
of how multiple libraries allow to create assertions. These libraries include https://github.com/google/guava[Guava] ,
https://github.com/apache/commons-lang[Apache Commons],
https://github.com/google/truth[Truth] & http://joel-costigliola.github.io/assertj/[AssertJ] as well as
https://gitlab.univ-nantes.fr/E203173Q/commons[the one we are currently building] as an extension to
https://gitlab.univ-nantes.fr/atlanmod/commons/[Atlanmod Commons].

== Examples : ==

A few examples of how to use each library.

xref:truth-examples.adoc[Examples of assertions from the Truth library ] +
xref:assertj-examples.adoc[Examples from the AssertJ library ] +
xref:guava-examples.adoc[Examples of preconditions from the Guava library ] +
xref:apache-commons-example.adoc[Example of guard closes from the Apache Commons library]


== Direct Comparisons ==

Direct comparisons of how each library is used to create the same suite of tests.

xref:handshake-tests.adoc[Comparisons of tests on associations and handshakes] +
xref:basicTestComparison.adoc[Comparisons of tests on a simple class]

=== Summary ===
_Explained in more details in the above links_ +

After these comparisons we came to the following conclusions